#9 login front end - Sign in and Sign up logic
Right-Pay/Software_Development_CS389 pull request #32
Opened 2023-10-05 15:37 UTC by Tibesnoff

- Sign in page has logic to allow a mock sign-in
- Sign up page has logic to allow a mock sign-up
- Both pages need calls to an API that needs to be created

2023-10-09 20:39 UTC, alexanderjhughes requested changes
Muy bueño

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/ForgotPassword.tsx
> +      <Text style={styles.titleTop}>Forgot your Password for</Text>
Use StylizedText with className="mt-30 font-20" or something like that instead of using a stylesheet at the bottom of the file. We should aim to get rid of these stylesheets.

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/ForgotPassword.tsx
>  const styles = StyleSheet.create({
Remove this, replace with TailwindsCSS

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/LogIn.tsx
> +  titleTop: {
Use tailwindsCSS

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/LogIn.tsx
> +      <Text
Needs to be a StylizedTouch, also should probably create a seperate component for the TouchButton if we have the same StylizedTouch with each button.

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Helpers/SignInError.tsx
> +        <Text style={styles.text} key={index}>
Use tailwindsCSS

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/ResetPassword.tsx
> +  useEffect(() => {
Move this to a global spot, I would not include this in the page.

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/ResetPassword.tsx
> +          clearSignInErrors();
I wouldn't clear the error until the user hits sign in again

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/ResetPassword.tsx
> +      <Button
Change to touchable

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/ResetPassword.tsx
> +  titleTop: {
TailwindsCSS

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/SignUp.tsx
> +import SignInError from '../../../Helpers/SignInError';
Maybe move SignInError in to AuthContext, that way you can control it from there.

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/SignUp.tsx
> +  const {clearSignInErrors, addSignInError, removeSignInError} =
Combine this with line 20, don't need two
```React.useContext(AuthContext)```

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/SignUp.tsx
> +      <Button
Touchable

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/VerifyEmail.tsx
> +      <Button
Touchable

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/VerifyEmail.tsx
> +const styles = StyleSheet.create({
TailwindsCSS

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Profile/ProfileSettings.tsx
> -      <Text style={styles.text}>Username: {userProfile.name}</Text>
We still want them to create a username as their "Display Name"

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Components/Screens/Profile/ProfileSettings.tsx
> -      <Text style={styles.text}>Username: {userProfile.name}</Text>
we can call it username though

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  const signIn = async (email: string, password: string) => {
Lets move all the auth contexts into another AuthState.tsx. Then we import GlobalState.tsx into the AuthState.tsx file and wrap the AuthContext.provider around the GlobalContext.provider.

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +        addSignInError('4');
I wouldn't use numbers, that can get a little confusing.

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +        addSignInError('4');
Maybe create a constants file and include the IncorrectEmailMessage constant at the top of file and pass it here.

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Helpers/accountAuthFunctions.tsx
> +import {Profile} from '../types/ProfileType';
Lets move these in to the new AuthState.tsx

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Helpers/SignInError.tsx
> +  const signInErrorMessages = new Map<string, string>([
Replace these with a constants file.

2023-10-09 20:39 UTC, alexanderjhughes commented on app/src/Navigation/MainNavigator.tsx
> +      <WelcomeStack.Screen name="VerifyEmail" component={VerifyEmailScreen} />
Me likely

2023-10-10 02:50 UTC, Tibesnoff commented on app/src/Components/Screens/Profile/ProfileSettings.tsx
> -      <Text style={styles.text}>Username: {userProfile.name}</Text>
I made the executive decision to make the username as the stuff before the @ in the email for now

2023-10-11 20:58 UTC, alexanderjhughes approved these changes

2023-10-11 20:58 UTC, alexanderjhughes commented on app/src/Components/Screens/Locked/ForgotPassword.tsx
> +const StylizedTouch = styled(Button);
Use touchable (native is stupid and wont let you style the button)

2023-10-12 14:10 UTC, merged