#14 created page template
Right-Pay/Software_Development_CS389 pull request #37
Opened 2023-10-08 23:51 UTC by Tibesnoff

Created page templates for component, api, and both

2023-10-09 22:56 UTC, alexanderjhughes requested changes
When generating a component with an api, couple quick questions.

1. Can we generate the components in the screen folder instead of generating a new sub folder named component? So instead of Screens -> Location -> components -> newComponent.tsx, instead we just put it in the Location directory. 
2. What do you mean by API? The API is the backend, I am just confused why we are calling it API on front end. Its just loading information from the server. 
3. Why segregate the fetch in a separate file? Why not just add it in the component file as a function. Imo its a little too much organizing and adds complexity. Maybe its good to have it this way idk. 

One other thing, creating just an api makes a directory called __name__(pascalcase) then puts the api in that directory.

2023-10-09 22:56 UTC, alexanderjhughes commented on app/tools/generate.js
> +/* eslint-disable quotes */
Lets not disable quotes, just keeps everything consistent

2023-10-09 22:56 UTC, alexanderjhughes commented on app/tools/templates/componentAndAPI/component/__name__.tsx
> +NativeStackScreenProps<__screen__NavigationRoutesType, '__screen__Screen'>,*/
add tab in front to fix eslint error on generating new file

2023-10-09 22:56 UTC, alexanderjhughes commented on app/tools/templates/componentAndAPI/component/__name__.tsx
> +NativeStackScreenProps<__screen__NavigationRoutesType, '__screen__Screen'>,*/
Would look like this
```
type __screen__ScreenProps = /*CompositeScreenProps<
  NativeStackScreenProps<__screen__NavigationRoutesType, '__screen__Screen'>,*/
  BottomTabScreenProps<NavigationRoutesType>
/*>*/ &
  PropsWithChildren;
```

2023-10-10 17:04 UTC, Tibesnoff commented
> When generating a component with an api, couple quick questions.
> 
> 1. Can we generate the components in the screen folder instead of generating a new sub folder named component? So instead of Screens -> Location -> components -> newComponent.tsx, instead we just put it in the Location directory.
> 2. What do you mean by API? The API is the backend, I am just confused why we are calling it API on front end. Its just loading information from the server.
> 3. Why segregate the fetch in a separate file? Why not just add it in the component file as a function. Imo its a little too much organizing and adds complexity. Maybe its good to have it this way idk.
> 
> One other thing, creating just an api makes a directory called **name**(pascalcase) then puts the api in that directory.



1. I think it has something to do with how it generates from a folder I will loook at it.
2. When I mean api I think I mean more just grabbing the backend. I personally think it may be better just to have these fetches seperate so component code doesn't end up being too long.

2023-10-10 17:14 UTC, Tibesnoff commented
> When generating a component with an api, couple quick questions.
> 
> 1. Can we generate the components in the screen folder instead of generating a new sub folder named component? So instead of Screens -> Location -> components -> newComponent.tsx, instead we just put it in the Location directory.
> 2. What do you mean by API? The API is the backend, I am just confused why we are calling it API on front end. Its just loading information from the server.
> 3. Why segregate the fetch in a separate file? Why not just add it in the component file as a function. Imo its a little too much organizing and adds complexity. Maybe its good to have it this way idk.
> 
> One other thing, creating just an api makes a directory called **name**(pascalcase) then puts the api in that directory.

I changed it up a lot and removed the api stuff as well as added tailwinds

2023-10-11 20:47 UTC, alexanderjhughes requested changes

2023-10-11 20:47 UTC, alexanderjhughes commented on app/src/Components/Screens/Search/SearchText.tsx
> +const StylizedTouch = styled(Text);
Use a TouchableHighlight, not Text: [Link to Docs](https://reactnative.dev/docs/handling-touches)

2023-10-11 20:47 UTC, alexanderjhughes commented on app/tools/templates/component/__name__.tsx
> +const StylizedTouch = styled(Text);
TouchableHighlight or a different touchable

2023-10-11 20:47 UTC, alexanderjhughes commented on app/tools/generate.js
> +        slot: '__folder__',
__stack__

2023-10-11 20:56 UTC, merged