#50 credit card front end
Right-Pay/Software_Development_CS389 pull request #75
Opened 2023-11-06 21:09 UTC by Tibesnoff

- Wallet screen displays fake credit cards
- Can add and delete cards
- Full card form flow
- Getting ready for the backend
- REWARDS ARE NOT DONE

2023-11-06 21:37 UTC, Tibesnoff commented on app/src/Context/GlobalState.tsx
> +    Search: false,
I may want to move this eventually

2023-11-08 20:54 UTC, alexanderjhughes requested changes
We somehow started using nodejs v18? We were supposed to stay on v16 but the newly added packages are for v18

2023-11-08 20:54 UTC, alexanderjhughes commented on app/App.tsx
> +export default RightPayApp;
Add a blank line at the end of file

2023-11-08 20:54 UTC, alexanderjhughes commented on app/android/app/src/main/AndroidManifest.xml
> +</manifest>
Add a blank line at the end of file

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Context/AuthState.tsx
> +    if (false) {
huh...

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Helpers/Consts.tsx
>  import ConstsType from '../types/ConstsType';
Need to start using i18n. Need a task for that for this sprint

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Helpers/Dropdown.tsx
> +    <View className={props.style}>
Needs to be a styled view in order for className to work

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Helpers/Dropdown.tsx
> +    props.options.map(o => ({
should add checks to make sure options is an array and I would set this in the initial load of the page ```useEffect( func, [] )```

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Helpers/StylizedComponents.tsx
> +const styledView = (styles: string) => styled(View, styles);
Not sure I understand why this is needed. Just do styled(View, styles) down below. This helper function adds overhead

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/types/CreditCardType.ts
> +  cardName: string;
These don't match what is being returned from the backend.

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/types/CreditCardType.ts
> +export interface CreditCardReward {
We will have to have a working session to go over this

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/types/DropdownProps.ts
> +export interface DropdownProps {
Just had an idea, lets add these interfaces in the bottom of each file, so for example for the custom dropdown, we put it at the bottom that way to import, we do:

```import DropdownComponent, {DropdownProps} from 'dropdownComponent.tsxt```

2023-11-08 20:54 UTC, alexanderjhughes commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
need to remove this file

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +  const onExpirationMonthDropdownChange = (item: string) =>
lets just use setExpirationMonth in the dropdown props. Creating a seperate method gets a little confusing

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardSearchForm.tsx
> +            Enter First Six Digits of your Credit Card Number
Should be a constant

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddNewDropdownOption.tsx
> +  function validateBank() {
These should be available somewhere globally I would think

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddNewDropdownOption.tsx
> +          <AuthButton onPress={closeModal} className="z-0">
Whats the AuthButton?

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/ReviewCreditCardForm.tsx
> +            <AuthInputBox
I am confused at the use of Auth components

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  const [rewards, setRewards] = React.useState<CreditCardReward[]>(
Rewards shouldn't be separate from Cards

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  const [creditCards, setCreditCards] = React.useState<CreditCard[]>(
This should be named cards, not creditCards as they can have debit cards too

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  const [creditCards, setCreditCards] = React.useState<CreditCard[]>(
Should be changed everywhere else too just noting it here

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +    Review: false,
I think we are overcomplicating these forms. We can just have 2 forms: enter bin (6 digits), review/edit pulled from database or add new fields.

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +    'Add New Type',
We won't be letting users add a new type. This is constant

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +    'Add New Bank',
We should add banks a different way. It should be above the bank dropdown something like 'Don't see your bank? Click here to request for your bank to be added'.

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +   * 3. If not found show full form. User will enter all info and send to db
2 and 3 can be combined

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +   * 4. Rewards will be found using a few details from card. Rewards review screen will show which will allow the user to enter rewards and see rewards already associated to that card. Send rewards t
Ahh I see, yea then we should have 3 screens, enter bin, review/edit/add card, review/edit/add rewards

2023-11-08 20:54 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  const addNewReward = (creditCardReward: CreditCardReward) => {
will have to review this, fine for now but not how rewards will get added.

2023-11-08 21:20 UTC, Tibesnoff commented on app/src/Context/AuthState.tsx
> +    if (false) {
I am just doing that because it is easier to switch

2023-11-08 21:21 UTC, Tibesnoff commented
> We somehow started using nodejs v18? We were supposed to stay on v16 but the newly added packages are for v18

Is there a way to update all packages to be node 16. I think it is just the deprecated props. Which I fixed on this current branch I am using for the settings.

2023-11-08 21:23 UTC, Tibesnoff commented on app/src/Context/GlobalState.tsx
> +    Review: false,
That would be three. Honestly I think it is nice how it is. It keeps it all separated and easy to debug.

2023-11-08 21:23 UTC, Tibesnoff commented on app/src/Context/GlobalState.tsx
> +    'Add New Bank',
Ya this is just temp because we will pull from the db

2023-11-08 21:24 UTC, Tibesnoff commented on app/src/Context/GlobalState.tsx
> +    'Add New Type',
Ah we aren't?? Okay I can change that. It'll simplify a lot of things.

2023-11-08 21:25 UTC, Tibesnoff commented on app/src/Context/GlobalState.tsx
> +   * 3. If not found show full form. User will enter all info and send to db
So you are saying nav to review screen no matter what and just have it blank? So review would be more like the add screen. The only thing is it may be tricky to differ if we add that card to the big card db or just the user db

2023-11-08 21:26 UTC, Tibesnoff commented on app/src/Context/GlobalState.tsx
> +  const addNewReward = (creditCardReward: CreditCardReward) => {
Ya I haven't done anything really with rewards yet. I am working on cards only and then will merge so you can connect backend then Ill do rewards front end pr then youll connect backend

2023-11-08 21:43 UTC, Tibesnoff commented on app/src/Components/Screens/Wallet/AddNewDropdownOption.tsx
> +  function validateBank() {
Shoot I forgot to move those. This is what reviews are for.

2023-11-09 20:10 UTC, Tibesnoff commented on app/src/Helpers/Dropdown.tsx
> +    props.options.map(o => ({
props.options can't not be an array. The props are typed

2023-11-09 20:12 UTC, Tibesnoff commented on app/src/Helpers/StylizedComponents.tsx
> +const styledView = (styles: string) => styled(View, styles);
I did it to make the code look a little cleaner but you are right

2023-11-10 01:43 UTC, alexanderjhughes requested changes

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +  const [nickname, setNickName] = React.useState<string>('');
nickName is still here

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +  const onCardTypeDropdownChange = (item: string) => setCardBrand(item);
Is there a reason we are using a sperate function here and not just passing setCardBrand into the prop

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +    if (item === 'Add New Bank' && newBankOption !== 'false') {
false shouldn't be a string, need to change this somehow, also 'Add New Bank' should be a const somewhere in this file that way there is no "magic" strings.

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +  const onCCNumberChange = (event: any) => {
onCNumberChange - turn CC into C

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +      errors.forEach(error => addAuthError(error));
Really should come up with a different error system, also these aren't auth errors?

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +      id: Math.random() * 100, //Will need to be updated to be unique
don't need this when making a new card

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +      card_name: cardName,
check api documentation, I will generate this on the backend using card bank, brand, and level

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +    setCardBin('');
Bin should be a number

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +    setExpirationMonth('');
should be numbers here too for year and month, date can be a string

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +    setBankOptions,
make this a pop up, get rid of Add New Bank

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +    if (item === 'Add New Bank' && newBankOption !== 'false') {
wait this shouldn't be there, do a pop up instead

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +    if (newBankOption !== '') {
need a different way of doing this, pop up option, not like this

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +          <Title>Add New Credit Card</Title>
Add New Card

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +            placeholder="Name of Card"
User is not entering name of card

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +            placeholder="First Six Digits"
so this is where we need to consolidate. Should be only this form for adding a card. What we can do is only show this input box to start, and hide the rest using a state called like showFullForm, then set that to true to show the rest. No need to make this file and the other as they are so similar

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardSearchForm.tsx
> +import React, {useEffect, useState} from 'react';
Combine with AddCreditCardFullForm.tsx (Should be called AddCardFullForm.tsx) for the future, if we fix all comments before resubmitting pr for review, it will make the process a lot quicker

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +                '12',
Eh, kinda hacky but looks good ig

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddNewBankOption.tsx
> +import React, {useEffect, useState} from 'react';
We will have to figure this out as we won't be taking whatever the user inputs and immediately put it into the DB, it will be reviewed first/put into a crowd sourcing table.

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/ReviewCreditCardForm.tsx
> +import React, {useEffect, useState} from 'react';
This should be combined with the AddCard

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/Wallet.tsx
> +          Add New Credit Card
Add New Card

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/Wallet.tsx
> +      {AddCreditCardFullForm()}
Combine these three

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/Wallet.tsx
> +      <CreditCardListView>
CardListView

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/Wallet.tsx
> +        <CreditCardList
CardList etc etc

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/Wallet.tsx
> +          snapToInterval={Dimensions.get('window').width + 48} //Change 48 based on width of CreditCardItemSeperator width
lets avoid magic number here if possible

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +    AddTypeOption: false,
What is AddType?

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  const [bankOptions, setBankOptions] = useState<string[]>([
Pull these from the database...

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  const [typeOptions, setTypeOptions] = useState<string[]>([
Pull these from the db

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  const [typeOptions, setTypeOptions] = useState<string[]>([
like in next branch

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +   * 3. If not found show full form. User will enter all info and send to db
So what I mean is we make one screen, it can be both add/edit(review). It just shifts what it does based on what it is doing.

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +   * 4. Rewards will be found using a few details from card. Rewards review screen will show which will allow the user to enter rewards and see rewards already associated to that card. Send rewards t
Nevermind, 2 screens, enter bin/review/edit/add card, and then review/edit/add rewards

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +      setCreditCardForms(c => ({...c, Full: true}));
so this logic would determine whether or not to hide or show the additional input forms

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  function testCardName(cardName: string) {
dont need this, cardName will be generated in db

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/Helpers/Dropdown.tsx
> +export interface DropdownProps {
I like the interface here 👍

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/types/AppContextType.ts
> +  creditCards: Card[];
all need to be cards, not creditCards

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/types/CreditCardType.ts
> +  date_card_linked?: string;
should put exp_date here

2023-11-10 01:43 UTC, alexanderjhughes commented on app/src/types/CreditCardType.ts
> +  card_bank?: string;
card_bank_id
card_bank_name
card_bank_abbr
not card_bank

2023-11-10 02:18 UTC, Tibesnoff commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +      errors.forEach(error => addAuthError(error));
I am keeping them there for right now. I really don't think it is a big problem for what we are working on currently. We have other things to worry about. Let's keep this in mind for later. And I used auth because technically they are authorizing the fields. Maybe we change the name to field error or something.

2023-11-10 02:20 UTC, Tibesnoff commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +      card_name: cardName,
Ya I see I just have it in for now because I haven't connected anything up yet

2023-11-10 02:25 UTC, Tibesnoff commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +    setExpirationMonth('');
I don't think this is going to matter much with how it's going from a string to a string. I am not really doing anything with the actual number after setting it. I am just going to leave it. Not really effecting code

2023-11-10 03:21 UTC, alexanderjhughes commented on app/src/Context/AuthState.tsx
> +    if (false) {
We should comment out things like this

2023-11-10 16:14 UTC, Tibesnoff commented on app/src/Components/Screens/Wallet/AddCreditCardFullForm.tsx
> +            placeholder="Name of Card"
They are if the card can't be found

2023-11-10 16:17 UTC, Tibesnoff commented on app/src/Components/Screens/Wallet/AddNewBankOption.tsx
> +import React, {useEffect, useState} from 'react';
Ya, I agree with this. I was thinking we make a rating system. So incase there is a private bank that only one or two user is using, they would still be able to use their bank. So maybe 1-5 once 5 people enter it in, that bank becomes public for anyone to use. If not it gets displayed only for that user each time they enter the bank in.

2023-11-10 21:58 UTC, Tibesnoff commented on app/src/Components/Screens/Wallet/ReviewCreditCardForm.tsx
> +import React, {useEffect, useState} from 'react';
I kind of like it how it is. I consolidated the add and search. I think it is fine. Because they have too much differnt logic. We need to just be done with this pr

2023-11-10 22:00 UTC, Tibesnoff commented on app/src/Context/GlobalState.tsx
> +  const [bankOptions, setBankOptions] = useState<string[]>([
Yup not at that stage yet

2023-11-10 22:01 UTC, Tibesnoff commented on app/src/types/CreditCardType.ts
> +  card_bank?: string;
Weren't we changing this?

2023-11-11 04:36 UTC, Tibesnoff commented on app/src/Context/AuthState.tsx
> +    if (false) {
Very true

2023-11-14 22:57 UTC, alexanderjhughes requested changes
These aren't meant to be mean ❤️ i just read over some and my wording isn't the best but its all supposed to be good.

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/types/CardType.ts
> +export interface Card {
Chefs kiss

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +    const fetchBanks = async () => {
This should be moved outside of useEffect and changed to a useCallback so we can use this in places other then just this initial useEffect hook.

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +      JSON.parse(content).data.forEach((b: CardBank) => {
Not sure why this has to be done? Yes the database needs cleaned up a bit but there will never be repeating bank names

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  }, [userProfile]);
good dependency

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +    const fetchBrands = async () => {
Should be outside of useEffect

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  function testExpirationDate(expirationDate: string) {
This isn't really a test, its a formatter

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  const removeCard = (card: Card) => {
Why would we remove a card?

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +    const createNew = async () => {
You can skip this and just pass the new card along with the linking to user. See [Linking Cards](https://github.com/Right-Pay/Software_Development_CS389/pull/87)

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +      const response = await fetch(`${baseURL}users/linkCard`, {
Needs to be in a try catch

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +      const content = await response.text();
Should be json

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +    console.log(content, 'find card');
add find card logic

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +      setCardInDB(true);
we eliminate this

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +    setNewCard(card);
This is hella overcomplicated

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/AuthState.tsx
>    useEffect(() => {
You can delete this before merging with main since it is deleted in the main.

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/AuthState.tsx
> +    setLang('en');
booooooo espanol on top

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/AuthState.tsx
> +
This is pretty redundant, no?

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Context/AuthState.tsx
> +            setUserToken(access_token);
good

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/ReviewCardForm.tsx
> +import React, {useEffect, useState} from 'react';
This should be combined with AddCardFullForm

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/ReviewCardForm.tsx
> +          card_bank_name: item,
Set bank id not bank name, see [Create Card](https://github.com/Right-Pay/Software_Development_CS389/pull/87)

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/ReviewCardForm.tsx
> +  //handers
handlers

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/ReviewCardForm.tsx
> +      card_bank_name: item,
bank_id

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/ReviewCardForm.tsx
> +      .filter(b => b.bank_name.toLowerCase().includes(item.toLowerCase()))
I would filter so it shows strings that have the current letters first, then strings that have the current letters anywhere else

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/ReviewCardForm.tsx
> +  const [filteredBankOptions, setFilteredBankOptions] = useState<string[]>([]);
I would use a useCallback instead of useState.
```
filteredBankOptions = useCallback(filterFn, [bank_name_search]);
```

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/ReviewCardForm.tsx
> +import React, {useEffect, useState} from 'react';
We can do that at a later date but I think it will simplify everything. That way while we are making changes to the bank search we don't have to clone it to each files

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddNewBankOption.tsx
> +import {
chefs kiss 💋

2023-11-14 22:57 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCardFullForm.tsx
> +import React, {useEffect, useState} from 'react';
Refer to comments in ReviewCardForm

2023-11-15 00:25 UTC, Tibesnoff commented on app/src/Context/GlobalState.tsx
> +      JSON.parse(content).data.forEach((b: CardBank) => {
There was some repeating

2023-11-15 01:10 UTC, Tibesnoff commented on app/src/Components/Screens/Wallet/ReviewCardForm.tsx
> +import React, {useEffect, useState} from 'react';
Makes sense. Or we make this someone else's problem

2023-11-15 08:17 UTC, alexanderjhughes approved these changes
I hope ya like, just cleaned it up a lot

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Helpers/Dropdown.tsx
> +    if (props.options) {
Updated to pass object to dropdown not list of strings

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Helpers/Dropdown.tsx
> +          listMode === 'MODAL' ? styleSheet.modalContainer : {}
Moved styles to stylesheet

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Helpers/Dropdown.tsx
> +    height: '33%',
Set to only partialy open

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +        if (tryAgain) {
Setting it so it trys again if auth token is expired

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +            bankOptions.find(b => b.id === +card.card_bank_id)?.bank_name ?? '',
Will incoporate this into the backend so you don't have to deal with it here

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +  const [rewards] = React.useState<Reward[]>(Consts.dummyCardRewards);
Simplified a lot of the use states that were in here that were unecessary

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCardFullForm.tsx
> +                {renderExpirationDropdown()}
Make it look purty

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCardFullForm.tsx
> +  const [card, setCard] = useState<Card>({} as Card);
Removed many of the unnecessary usestates from here

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCardFullForm.tsx
> +  }
This is what we will use to do the review and add in the same file. Edit is really 'review'. If any field changes, it changes to the add state so it adds a new card even if it has the same bin number

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCardFullForm.tsx
> +        setFilteredBankOptions([]);
This is where the error occurs atm with the dropdown showing up on the new screen.

2023-11-15 08:17 UTC, alexanderjhughes commented on app/src/Components/Screens/Wallet/AddCardFullForm.tsx
> +  // }, []);
Not allowing users to add banks atm

2023-11-15 20:13 UTC, merged