#76/#36 settings profile
Right-Pay/Software_Development_CS389 pull request #94
Opened 2023-11-24 01:21 UTC by Tibesnoff

Settings and profile page was completed
Some code was refactored

- Home screen purged and moved to profile mostly
- Profile shows user profile and has buttons to logout and go to settings

- Settings screens were created to reflect the settings they hold
- Profile allows for editing profile however this only works frontend and does not get saved to the backend as that is not created yet
- General has a toggle to send to location settings toggle and will update the location accordingly
- More settings sends you to same settings page but just makes it quick. All these settings are not used currently that is why they are set how they are
- Card settings allows for deletion of cards currently. This is just another location to see a quick view of your cards and delete. It will also allow editing eventually when this is supported. I am thinking it will just pop the form up again and will allow editing of card. Not sure if this is a good idea or not. I think this could just be an edit and send to backend. I am just not sure if we should even bother with allowing to edit. I want to put this in a separate pbi because I'd just be wasting time working on it.

- A lot of code was refactored
- Edited stylized components to make it read nicer
- Added a new location context to give a shorter app context. I am thinking we do the same for cards

I have not tested this on android. Hopefully it works. I don't know why it wouldn't

2023-11-25 03:46 UTC, alexanderjhughes requested changes
looks good, some minor changes and we are good to push

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Components/Screens/Location/Location.tsx
> +import locationContext from '../../../Context/locationContext';
Why is this a part of this pr?

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Components/Screens/Profile/Settings/GeneralSettings.tsx
> +          <Switch
Not a very good switch input but we can work with it for now

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Components/Screens/Profile/Settings/ProfileSettings.tsx
> +  const handleSave = () => {
Feel like this is overly complicated logic but it works for now

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Components/Screens/Profile/Settings/ProfileSettings.tsx
> +        value={formData[field as keyof typeof formData]}
if we have an empty phone number, I would say lets not show it at all

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Helpers/Consts.tsx
> +  routes: {
Ooh we shouldn't do it like this

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Components/Screens/Profile/Settings/Settings.tsx
> +  };
Why are we using a const file for the routes? All the routes should be typed which means we don't need a const file

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Components/Screens/Welcome/ForgotPassword.tsx
> +import KeyboardAvoidingViewScroll from '../../../Helpers/KeyboardAvoidingViewScroll';
Should have made a seperate pr for this

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Components/Screens/Welcome/LogIn.tsx
> +import KeyboardAvoidingViewScroll from '../../../Helpers/KeyboardAvoidingViewScroll';
Separate PR

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Components/Screens/Welcome/SignUp.tsx
> +import KeyboardAvoidingViewScroll from '../../../Helpers/KeyboardAvoidingViewScroll';
Sep PR

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Context/AuthState.tsx
> +            const cards = profile.cards.sort((a, b) => {
Do we really want to sort like this? With the current way, we sort by least recent to most recently added to db. We should probably swap that but idk if we should short by card bin

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Context/AuthState.tsx
> +        setUserProfile,
Are we using this elsewhere in the project? If not we should not be exporting it like this.

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Components/Screens/Profile/Settings/ProfileSettings.tsx
> +          setUserProfile({...userProfile, [key]: formData[key]});
Should not directly set userProfile here

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Context/GlobalState.tsx
> +import LocationState from './LocationState';
Separate pr..........

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Context/LocationState.tsx
Separate pr

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Helpers/KeyboardAvoidingViewScroll.tsx
Separate PR

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Helpers/StylizedComponents.tsx
We should not generalize the styles like this. When we first did it this way I was told this is how we will do it but it is not efficient at all right now.

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/Navigation/TabNavigator.tsx
> +import {View} from 'react-native';
Why is this imported here?

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/types/AuthContextType.ts
> +  setUserProfile: (_userProfile: Profile) => void;
Lets not export it here

2023-11-25 03:46 UTC, alexanderjhughes commented on app/src/types/ConstsType.ts
> +  [key: string]: string;
These `[key: string]: string;` are used many times in this file and are unnecessarily repeated. Lets condense.

2023-11-25 14:04 UTC, Tibesnoff commented on app/src/Components/Screens/Profile/Settings/GeneralSettings.tsx
> +          <Switch
This switch was very customizable but I don't like it either. The react native one was nice but you couldn't customize it real well without it looking weird.

2023-11-25 14:06 UTC, Tibesnoff commented on app/src/Helpers/Consts.tsx
> +  routes: {
This and the routes I added to the costs for ii18n or whatever it is. If you don't want me to do it like that its fine, I'll move it. I thought you were saying to not have any magic text strings. I'll take it all out for a future pbi

2023-11-25 14:17 UTC, Tibesnoff commented on app/src/Context/AuthState.tsx
> +            const cards = profile.cards.sort((a, b) => {
I don't have to have it sort like this. Just an idea. It does take to much time.

2023-11-25 14:19 UTC, Tibesnoff commented on app/src/Components/Screens/Profile/Settings/ProfileSettings.tsx
> +          setUserProfile({...userProfile, [key]: formData[key]});
This is more of a temporary because we don't have anything in the db. I will make a refresh userProfile function that will just repull from the db. This flow would be create a new profile. Upload to db then do that refresh.

2023-11-25 15:42 UTC, Tibesnoff commented on app/src/Components/Screens/Profile/Settings/ProfileSettings.tsx
> +          setUserProfile({...userProfile, [key]: formData[key]});
I think what I did works as a boilerplate for now

2023-11-25 15:43 UTC, Tibesnoff commented on app/src/Helpers/StylizedComponents.tsx
Can we have a talk about this sometime next week. I just want to be on the same page. Maybe we have a task to fix all this. I recently found out you can just add classnames to normal <View> etc so maybe we change this up a bit. I am not sure

2023-11-25 15:43 UTC, Tibesnoff commented on app/src/Navigation/TabNavigator.tsx
> +import {View} from 'react-native';
Because I am dumb

2023-11-25 15:44 UTC, Tibesnoff commented on app/src/Components/Screens/Profile/Settings/ProfileSettings.tsx
> +  const handleSave = () => {
I hope what I did fixes it. It looks long but it avoids changing values into keys and such. I used enum instead

2023-11-27 18:38 UTC, alexanderjhughes commented on app/src/Helpers/Consts.tsx
> +  routes: {
No I mean the routes not the text for the label of the buttons.

2023-11-27 18:44 UTC, alexanderjhughes requested changes

2023-11-27 18:44 UTC, alexanderjhughes commented on app/src/types/ConstsType.ts
This file still has repeat types with AuthErrorMessages and DropdownListModes

2023-11-27 18:44 UTC, alexanderjhughes commented on app/src/Components/Screens/Profile/Settings/Settings.tsx
> +  ];
When I said eliminate the routes type, I mean get rid of the settingsPages.route part of the strings from the const file. You can still keep the settingsPages.name in the cosnt file.

2023-11-27 21:45 UTC, merged